article-4-direction:
- reference
- name
- document-url
- documentation-url
article-4-direction-area:
- reference
- geometry
- name
- permitted-development-rights
conservation-area:
- reference
- geometry
- name
conservation-area-document:
- reference
- name
- conservation-area
- document-url
- documentation-url
- document-type
tree-preservation-order:
- reference
- document-url
- documentation-url
tree-preservation-zone:
- reference
- geometry
listed-building-outline:
- reference
- geometry
- name
- listed-building
tree:
- reference
-
  - point
  - geometry
brownfield-land:
- OrganisationURI
- SiteReference
- SiteNameAddress
- GeoX
- GeoY
developer-agreement:
- reference
developer-agreement-contribution:
- reference
developer-agreement-transaction:
- reference
infrastructure-funding-statement:
- reference
